// Author identity stamped on autocommits. Real user identity comes
// from settings in 13e; until then commits are attributed to the app.
export const DEFAULT_GIT_AUTHOR = {
  name: 'mi-cerebro',
  email: 'mi-cerebro@local',
} as const;

// .gitignore written on first init. Heavy binaries and safety-net
// directories that should never enter history. See PROYECTO.md §12
// ("Autocommits") and §19 paso 13a.
export const DEFAULT_GITIGNORE = `# mi-cerebro autogenerated
# Heavy binaries
music/tracks/
images/*/original/

# Safety nets — never enter history
.mi-cerebro/recovery/
.mi-cerebro/pre-migration/
.mi-cerebro/trash/
.mi-cerebro/history/
`;
